napvig:
  step_ahead_size: 2.0
  gradient_step_size: 6.9
  termination_distance: 0.07
  termination_count: 50
  prediction_window: 4
  method: goal # {straight, goal}
landscape:
  measure_radius: 5.9
  smooth_radius: 0.1
  precision: 1000
  dimensions: 3
  decimation: 100
  min_distance: 1.5