napvig:
  step_ahead_size: 0.4
  gradient_step_size: 0.9
  termination_distance: 0.07
  termination_count: 50
  prediction_window: 4
  method: goal # {straight, goal}
landscape:
  measure_radius: 0.9
  smooth_radius: 0.05
  precision: 1000
  dimensions: 3
  decimation: 100
  min_distance: 0.3