napvig:
  step_ahead_size: 0.5
  gradient_step_size: 0.3
  termination_distance: 0.07
  termination_count: 50
  prediction_window: 4
  method: goal # {straight, goal}
landscape:
  measure_radius: 2.0
  smooth_radius: 0.1
  precision: 100
  dimensions: 3
  decimation: 5
  min_distance: 1.5